== Standalone Java Functions

These are self contained Java functions, each implements `java.util.function.Function` and can be used as a component that provides a value for a given input value in a variety of streaming application platforms such as Spring Cloud Data Flow, Project RIFF etc.
The functions can be run as part of standalone Spring Boot applications.

=== Available Functions

`splitter-function`

This is a "one-to-many" Java function with a signature as `Function<Message<?>, List<Message<?>>>`. So, every inbound message is splitted into several output messages.
This function is fully based on the Spring integration `AbstractMessageSplitter` and supports a `delimiters`, `expression`, `applySequence` properties.
Also if one of the `fileMarkers` or `charset` properties is present, the `FileSplitter` implementation is used and an incoming payload is treated as file for splitting.

`spel-function`

Transform incoming message payload based on a SpEL expression and produces an outbound message.

`filter-function`

Filter an incoming message based on a boolean SpEL expression and produces that message or nothing according expression result.
